services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: 'vul_db'
      MYSQL_USER: 'vul_user'
      MYSQL_PASSWORD: 'vul_password'
      MYSQL_ROOT_PASSWORD: 'vul_root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
